export default defineAppConfig({
    ui: {
        colors: {
            primary: 'violet',
            secondary: 'pink',
            success: 'lime',
            info: 'cyan',
            warning: 'amber',
            error: 'rose',
            neutral: 'slate',
            red: 'red',
            orange: 'orange',
            amber: 'amber',
            yellow: 'yellow',
            lime: 'lime',
            green: 'green',
            emerald: 'emerald',
            teal: 'teal',
            cyan: 'cyan',
            sky: 'sky',
            blue: 'blue',
            indigo: 'indigo',
            violet: 'violet',
            purple: 'purple',
            fuchsia: 'fuchsia',
            pink: 'pink',
            rose: 'rose',
            slate: 'slate',
            gray: 'gray',
            zinc: 'zinc',
            stone: 'stone'
        },
        icons: {
            arrowDown: 'i-ph-arrow-down',
            arrowLeft: 'i-ph-arrow-left',
            arrowRight: 'i-ph-arrow-right',
            arrowUp: 'i-ph-arrow-up',
            caution: 'i-ph-warning',
            check: 'i-ph-check',
            chevronDoubleLeft: 'i-ph-caret-double-left',
            chevronDoubleRight: 'i-ph-caret-double-right',
            chevronDown: 'i-ph-caret-down-bold',
            chevronLeft: 'i-ph-caret-left-bold',
            chevronRight: 'i-ph-caret-right-bold',
            chevronUp: 'i-ph-caret-up-bold',
            close: 'i-ph-x',
            copy: 'i-ph-copy',
            copyCheck: 'i-ph-check-square',
            dark: 'i-ph-moon',
            drag: 'i-ph-dots-six-vertical',
            ellipsis: 'i-ph-dots-three',
            error: 'i-ph-x-circle',
            external: 'i-ph-arrow-square-out',
            eye: 'i-ph-eye',
            eyeOff: 'i-ph-eye-slash',
            file: 'i-ph-file',
            folder: 'i-ph-folder',
            folderOpen: 'i-ph-folder-open',
            hash: 'i-ph-hash',
            info: 'i-ph-info',
            light: 'i-ph-sun',
            loading: 'i-ph-spinner',
            menu: 'i-ph-list',
            minus: 'i-ph-minus',
            panelClose: 'i-ph-layout-sidebar',
            panelOpen: 'i-ph-layout-sidebar',
            plus: 'i-ph-plus',
            reload: 'i-ph-arrow-clockwise',
            search: 'i-ph-magnifying-glass',
            stop: 'i-ph-stop',
            success: 'i-ph-check-circle',
            system: 'i-ph-monitor',
            tip: 'i-ph-lightbulb',
            upload: 'i-ph-upload',
            warning: 'i-ph-warning-circle',
        },
        button: {
            base: 'rounded-full',
            variants: {
                size: {
                    lg: {
                        base: 'text-base px-6 py-3',
                    },
                },
            },
            defaultVariants: { size: 'lg', variant: 'solid' },
        },
        input: {
            base: 'rounded-full font-bold',
            variants: {
                size: {
                    lg: {
                        base: 'text-base px-6 py-3',
                    },
                },
            },
            defaultVariants: { size: 'lg' },
        },
        textarea: {
            base: 'rounded-full',
            defaultVariants: { size: 'lg' },
        },
        select: {
            base: 'rounded-full',
            defaultVariants: { size: 'lg' },
        },
        badge: {
            base: 'rounded-full',
            defaultVariants: { size: 'lg' },
        },
        avatar: {
            defaultVariants: { size: 'lg' },
        },
        kbd: {
            defaultVariants: { size: 'lg' },
        },
    },
})